#+TITLE: 两个奇怪的梦，却像极了生活
#+SETUPFILE: ../setup/theme-readtheorg-local.setup
#+OPTIONS: toc:nil

也许和生活没有丝毫关系，只是我梦醒后，臆想而已，毕竟梦是大脑活跃的结果，醒来想到什么都是可能的。

* 第一次梦到了丧尸
其实一点也不可怕，完全没有生化危机里的恐怖，反而有点滑稽。

梦的开头我处在一个实验室，这是个生化实验室，估计是用基因工程改造人的，毫无悬念，试验要失败，丧尸要出现，实验室的人非常清楚这点，似乎这就是他们试验的目的。我也非常清楚这点，但是我并没有走。别人都在忙着试验，我像个局外人，直到丧尸出现。实验室的人指挥丧尸来吃我（终于不是局外人了），当然，在梦里，咱是不能让丧尸欺负了的。丧尸总是想啃我肩膀，我就掐着丧尸的脖子，让他不能够着我。这是一个廋弱的女丧尸，被我掐着脖子，脑袋像点头似的不断向我发动徒劳的进攻。梦里我也使不上劲儿，不能像爱丽丝一样打死丧尸，我们就这么耗着，我心里想：要不让丧尸吃了我吧，这样耗着挺累的。

到这里就开始第二个梦了。都说梦是心头想，但是关于这个梦，我觉得我想得有点多了。丧尸是人为造出来，我知道这个，竟然不提前逃命。难道这个丧尸就是吃人的社会，我无处可逃，我再和它做着抗争，并随时可能坚持不下去，想让丧尸痛快痛快。可怕的是这个丧尸，也就是吃人的社会是人为造出来的。

* 第二次梦到了租房
第二次我在一个地方打工，收工的时候，工友要去地下室，他很诧异我没跟他一起下去（难道地下已经形成了一个世界，某类人住那里理所当然）。我得意的走了，内心的想法一定是老子有钱，我住地上（梦里任性）。我第一次去租的房子那里，一路走过去，地上的房子各种老破小，还奇葩。我推门到我租住的地方，一家三口人正在吃饭，孩子7，8岁的样子。这是一个开间，隔出一个卧室（仅能放一个床），一个极小的杂货间，剩下的地方做着床，厨具，餐桌。地板是木头的，靠近厨具的地方已经坏掉，露出水泥地面，没坏的部分油腻腻的。

男主人看我进来，拿起拖把拖地，但是怎么拖也拖不干净，因为沾了水，地面反而显的更脏了。我劝说到：有的地板脏了，是很难再拖干净的。男人于是坐到了炉子边（烧煤球的那种），一脚踩到炉子边沿上。家里的儿子拿着拖把倔强的继续拖，小孩子也要自尊，地面的确太脏了。男人有点虚胖，看起来是个卡车司机，在这个城市，开车司机收入并不高。聊天时他不小心把脚滑了下来，掉到了炉子边上的水里，把布鞋沾湿了。

这时梦醒了。我就想这间房子，人家一家三口住的好好的，我怎么会租在这里？我想大约是，他们生活窘迫，不得已把一间出租出去。而我本来应该住地下室的，就租了这么一个尴尬的地方。这个城市大约地价奇高，低收入者只能住地下室，估计是外来务工的居多。很多勉强能在地上居住的人，也随时会沦落到住地下室的地步，只是可怜了孩子。那些中上阶层的住所没有梦到，大约和北京是类似的。

* 为什么梦里有孩子
估计是因为我有孩子。很多人都宣称不要孩子，并不是因为想丁客，而是因为，我的生活已如此艰难，就别带他到世上受苦了吧。有的生活不那么艰难的人，因为社会不如意，也不想让孩子出生受罪。我也认同这种想法，但我有孩子。

这世界有星辰大海，就算花费不起，哪怕随便找个免费公园，花一块钱买个馒头去喂鱼都充满乐趣。世界可能在变好，也可能在变坏，但都是人造出来的。我们不能让蛀虫毁掉这个世界，我们要努力，要有孩子，带他领略世间的好，改善世间的不好。

我希望科技进步，生产力高度发达，第二个梦永远是梦，就算穷人，也可以体面。
