#+TITLE: 关于我
#+SETUPFILE: ../setup/theme-readtheorg-local.setup
#+OPTIONS: toc:nil

* 基本信息
男，84年生，07年毕业于中国矿业大学数学系，后在互联网行业从事开发，架构工作至今。

* 基本技能和所擅长
- 丰富的linux c、c++、golang系统开发、调试、调优经验，良好的开发习惯。此外有bash、lua、perl、java、erlang等有编程经验
- 丰富的系统架构，设计经验。系统内模块儿化，系统间解耦，分层设计，可运维、可监控、易调试系统的构建，经验丰富。对老系统的重构，新系统的旁路测试，新旧系统的平滑升级也有丰富经验
- 对非阻塞，多进程，多线程，多协程对高并发的影响有丰富经验
- 深入理解数据结构、算法、分布式系统、大数据、数据库、网络等，对机器学习有一定了解。
- 对高效团队建设，需求分析，产品落地，有一定经验
- 基于vue、bootstrap做前端开发

* 工作经历
** 搜狗，2014年10月 - 至今
在搜狗，技术的深度和广度有所深入，以用户导向，结果导向的方式思考问题。

16年以前我专注开发。16年到18年我像架构师，专注团队效率和业务。18年以后专注做成事，架构、开发、产品、客服啥都干。

*** datalink系统， 2018年4月 - 至今
前身是搜狗监控系统，但过于陈旧。历时一年重新实现了新监控，在新旧系统升级过程中，形成了“立足监控，促进业务稳定，立足度量，做开放数据”的产品思路。产品覆盖公司80%以上的业务。

*** 搜狗应用平台，2020年1月 - 2020年7月
类似SaaS，对于activemq，elasticsearch，kafka等标准应用，用户只需配置，即可使用，无需运维。
此为个人发起的项目，初衷是让业务开发专注业务，标准应用有开箱即用的方案，同时集中运维也利用提升稳定性和资源利用率。

*** dfly系统，2019年7月 - 至今
dfly系统是搜狗的自动化运维系统，我负责agent及其插件部分。
agent部署在业务机器上，负责接收系统指令，并调用插件执行指令。其中gravity插件最核心，负责配置管理。

*** plus项目， 2017年3月 - 2018年4月
这是一次构建数据中台的尝试。主要产品包括业务指标统计、数据市场、数据分析。作为架构师和产品参与其中，并作出MVP。
业务指标统计涵盖了sdk采集，服务端计算，采用传统的hadoop。数据市场是整理搜狗的数据资产，实现跨部门的数据合作。数据分析提供即席查询，基于hive+presto，数据来源于用户上传。
没做成挺可惜的，中台不是技术问题，是公司组织问题。

团队效率方面，模板化了spring框架，以及使用规范，标准化了文档，测试，监控，排错，部署等。

*** 云图重构和redis平台，2014年10月 - 2016年3月

- 云图系统重构，重构后的API更功能强大，系统组件由nginx-lua加php改为纯nginx-lua，为API添加了全套的自动化测试。
- redis平台，为中等规模用户提供一键开启，免运维的redis服务。基于原生redis、zookeeper、lvs开发。

** 云栈科技， 2013年10月 - 2014年10月
作为初级合伙人，参与公司产品开发，基于公有云的运维管理平台。因公司转型做新产品，无意于此，故退出。

** 新浪，2007年7月 - 2013年10月
在新浪，个人成长偏技术方面，以技术导向的方式思考问题。

*** SAE运维主管， 2012年12月 – 2013年11月
Sae运维团队缺人，就去带了一年运维团队，一年内实现了全部的管理puppet化。

*** SAE系统开发工程师， 2009年3月 – 2012年12月
09年开始从事sae的开发，sae是国内领先的PaaS云平台，作为sae最早的员工和核心开发者，主导了sae很多核心组件的开发，并为sae的持续改进和稳定运行做出了努力。

主要工作有：
- 开发sae的L7，对负载均衡非常了解
- 开发trigger，是sae各主要系统的控制数据源
- 开发sae的缓存系统memcachedx
- 开发sae的用户代码分发系统codefs
- 开发sae的对外http，tcp代理
- 开发sae的apache环境

* 个人项目
https://github.com/zzyongx 是个人的github，比较有意思的几个项目是：
- shmc 是一个基于共享内存的key-value库，其中包换了一个网络操作接口，使得数据可以通过net和语言级的api同时访问，某些场景下，极大提高性能
- Wayd是一个apache模块，在prefork模式下可以显示当前进程正在服务那个请求，利于调试和排障
- tail2kafka，可以实时把文件内容发往kafka和es，发送前，支持通过lua修改文件内容
- dcron，实现简单的分布式任务调度
