#+TITLE: datalink 系统设计思想
#+SETUPFILE: ../setup/theme-readtheorg-local.setup
#+OPTIONS: toc:nil

任何业务，凡是为用户提供服务，无不追求稳定和高可用。因为这样的业务才能为用户创造价值，为公司赚取利润。然而，热力学第二定律告诉我们系统的熵总是不断增大的，熵增大必然导致稳定性降低。例如：硬件老化，软件技术债，数据膨胀，这些都会降低业务系统的稳定性。

datalink 为业务提供多维度监控，及时发现问题。同时提供实时可观察性，专家经验，内部事件关联等，以快速解决问题，缩短故障时间，甚至提前发现问题。

* datalink的通俗化解释
为了让非IT人员，了解datalink，下面使用 *人* 类比 *业务* ，了解datalink能做什么。

** 异常提醒
“发热”对人来说至关重要，因为它是一个重要指标，提醒人发生了某些问题。业务系统也是如此，有很多指标表明其是否健康，与“发热”不同的是，这些指标不会让业务人员“发热”，我们必须借助监控报警系统来发现这些指标异常，进而通知业务人员修复问题。

** 可观察性
古代医生诊断问题，主要通过“望闻问切”，和现代医学所能使用的验血、CT、B超、核磁相比，古人能做的太有限。现代医学的先进设备，提高了人体的可观察性，可以更快，更全面的了解人的身体状况。系统也是如此，可观察性越好，越容易发现问题，解决问题。

** 专业经验
普通医生在成长为专家前，一定接触过非常多的病人，遗憾的是专家的知识只能传承，专家本人没法复制。软件不是这样，datalink这样的系统，见得多了，能沉淀在系统内的专业知识越多，能帮助业务的地方就越多。

** 信息壁垒
一个肚子疼的病人，如果主动告诉医生自己胃一向不好，并且昨天喝了很多酒，那么医生可能会更有方向。业务系统也是如此，IaaS故障、SaaS升级，关联业务变更等都可能引起业务系统不稳定，但IaaS，SaaS，关联业务可能是不同部门的人负责的，datalink可以打破部门之间，不同业务系统之间的信息壁垒，可以更快定位不稳定的根源。

** 数据面板
定时体检是必要的，如果不是成本，无时无刻都在体检不是更好。业务系统的处境好多了，只需很低的成本，datalink可以细粒度的收集业务系统的很多指标，展示在面板上，对指标做预警。

* datalink的专业化解释

datalink系统集成并自动化了基础设施监控、应用程序性能监控和日志管理，为业务的整个技术堆栈提供实时可观察性，同时沉淀专家经验，打破信息壁垒，旨在解决云时代的规模、复杂性和动态性质，以提升业务系统的可用性，为用户创造价值。

* datalink使用的技术
1. agent，基于开源的node_exporter，添加了非常多的功能，例如日志，进程，第三方数据，k8s等，是数据采集的核心。
2. prometheus集群，把prometheus做成集群，以应对数以4万+的机器，每天多达2T的指标数据。
3. 根因日志，借助agent，es，tail2es等组件，高效的收集报警关联的日志。
4. golang 开发核心api，关联agent，prometheus，根因日志等子系统。

* datalink的现状
目前datalink在基础设施监控，应用程序性能监控和日志管理方面，沉淀专家经验等后端技术基本成型，专业用户很容易使用。在打破信息壁垒方面做了探索，并应用在了KPI监控，还有很多工作要做。数据面板方面非常薄弱，仅能满足基本需求。

** 强项
无所不能的指标采集，细粒度的指标数据，灵活的指标报警，做到了只有不想监控的，没有监控不了的。

** 不足
1. 普及度不够，算不上一个公司级产品，很多人有需求，但是不知道datalink这个产品
2. 用户交互不够友好（学习曲线陡峭）

** 面向未来
1. 改进用户交互，让用户一看能用
2. 推广，这个一需要datalink自身改进，二需要时间慢慢渗透

** 收益
1. 提升业务稳定，主要在预警，专家经验方面
2. 缩短业务故障时间
