#+TITLE: 开发环境
#+OPTIONS: toc:nil
#+SETUPFILE: ../setup/theme-readtheorg-local.setup

* windows
** swan-desktop
基于cygwin的xfce桌面，xfce4-terminal 很好用，支持标签。[[http://www.starlig.ht/][swan-desktop]]

*** 安装fish
fish是一个比较好用的shell ~spm -i fish~ 。但是安装官方建议放到 =.bash_profile= 的最后， =Swan Xfce4 Desktop= 可能无法启动。 手动 =exec fish= 也许是个好主意。

*** 支持中文
1. 安装ibus =spm -i ibus= =spm -i ibus-pinyin=
2. 在 *会话和启动* 中配置ibus启动 =ibus-daemon=
3. 在 =.bash_profile= 中配置 ~export GTK_IM_MODULE=ibus export XMODIFIERS=@im=ibus export QT_IM_MODULE=ibus~

*** 启动windows程序
1. 配置windows别名 ~alias chrome='/cygdrive/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome'~
2. 配置pandoc别名 ~alias chrome='/cygdrive/c/Users/zhengzhiyong/AppData/Local/Pandoc/pandoc'~

** FAQ
*** 使用spm报错
$ spm -i vim-minimal
Unable to start 'C:\Users\zhengzhiyong\AppData\Roaming\Swan\.cache\spm\setup-x86_64.exe': The operating system denied access to the specified file.

修正方法：
1. 删除 setup-x86_64.exe
2. spm -u

* linux
** 安装开发工具
~apt-get install pstack~

** 安装emacs的图形依赖
~sudo apt-get install build-essential texinfo libx11-dev libxpm-dev libjpeg-dev libpng-dev libgif-dev libtiff-dev libgtk2.0-dev libncurses-dev chromium-browser~

** 终端在tab中打开标签
在终端菜单 编辑->首选项 中配置

** 配置vpn
#+BEGIN_SRC bash
apt-get install vpnc
F=/usr/local/bin/vpnc.start; echo -e '#!/bin/bash\nvpnc /etc/vpnc/default.conf' > $F; chmod a+x $F
#+END_SRC

** 配置=bash_profile=
export PS1="[@zzyong \W]\$ "

* golang
#+BEGIN_SRC bash
tar -C /usr/local -xzf go1.12.6.linux-386.tar.gz
echo 'export PATH=/usr/local/go/bin:$PATH' >> ~/.bash_profile
echo 'export GOPATH=/data/zzyong/gitlab' >> ~/.bash_profile
#+END_SRC

* vscode
1. =sudo add-apt-repository ppa:ubuntu-desktop/ubuntu-make=
2. =sudo apt-get update=
3. =sudo apt-get install ubuntu-make=
4. =umake ide visual-studio-code=

* apt
1. =apt list --installed= 列出所有已安装的软件


* json
** gofx
[[https://github.com/antonmedv/gofx][gofx]] 是一款命令行json处理工具，可以 =格式化= json，和用 =jsonpath= 类似的方法获取json片段。

** 浏览器DevTools
=DevTools= 是浏览器提供的开发者调试工具，可以在它的控制台执行交互式js。首先把json加载到json变量里， =fetch("...").then(r => r.json()).then(j => json = j)= 现在可以使用js随意操作json了。

* android without ide
1. =sudo apt-get install openjdk-8-jdk-headless=
